spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./user-transactions;Mode=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: true
    changeLog: 'classpath:db/changelog/db.changelog-master.xml'

logging:
  level:
    org:
      springframework:
      web: DEBUG
      hibernate: ERROR

server:
  port: 8082
  servlet:
    context-path: /api/user-transactions

hibernate:
  format:
    sql: true
